# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener:  true
    allowed_methods_listener:  true
    routing_loader: false
    view:
        view_response_listener:  true
    body_converter:
        enabled: true
    format_listener:
        rules:
            - { path: ^/api/v1, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
            - { path: ^/, priorities: [ 'html', '*/*' ], fallback_format: html, prefer_extension: true }
    service:
      serializer: fos_rest.serializer.jms