#index:
#    path: /
#    controller: App\Controller\DefaultController::index

campervan:
  prefix: /api/v1/
  resource: "routes/api/v1/campervans.yaml"

potable_eqipment:
  prefix: /api/v1/
  resource: "routes/api/v1/potable_eqipments.yaml"

potable_eqipment_type:
  prefix: /api/v1/
  resource: "routes/api/v1/potable_eqipment_types.yaml"